#framework:
    #secret: '%env(APP_SECRET)%'
    # Activation des annotations
    #annotations:
        #enabled: true
when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
